# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('E', '영어'), ('K', '한국어')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'Slide'), ('P', 'PDF'), ('V', 'Video')], max_length=1)),
                ('location', models.CharField(max_length=255)),
                ('ORDER', models.IntegerField(default=0, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Program')),
            ],
        ),
    ]
